name: Validate Template Submissions

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'templates/*.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate-template:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Add template:')
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          templates/*.json
        files_ignore: |
          !templates/*.json

    - name: Check safe changes
      run: |
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
        echo "Template files changed: ${{ steps.changed-files.outputs.any_changed }}"
        echo "Non-template files changed: ${{ steps.changed-files.outputs.other_changed_files }}"
        
        # Check if only template files changed
        if [[ "${{ steps.changed-files.outputs.other_changed_files }}" != "" ]]; then
          echo "❌ Non-template files detected: ${{ steps.changed-files.outputs.other_changed_files }}"
          echo "SAFE_CHANGES=false" >> $GITHUB_ENV
        else
          echo "✅ Only template files changed"
          echo "SAFE_CHANGES=true" >> $GITHUB_ENV
        fi
        
        # Save changed template files for validation
        echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt

    - name: Validate template files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Validating template submissions..."
        valid=true
        
        # Install jq for JSON validation
        sudo apt-get update && sudo apt-get install -y jq
        
        # Process each changed template file
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Validating $file"
          
          # Check if file exists
          if [[ ! -f "$file" ]]; then
            echo "❌ File $file does not exist"
            valid=false
            continue
          fi
          
          # Validate JSON structure
          if ! jq empty "$file" 2>/dev/null; then
            echo "❌ File $file is not valid JSON"
            valid=false
            continue
          fi
          
          # Check required template fields
          if ! jq -e '.id and .name and .images and .tiers' "$file" >/dev/null; then
            echo "❌ File $file missing required template fields (id, name, images, tiers)"
            valid=false
            continue
          fi
          
          # Check template ID matches filename
          template_id=$(jq -r '.id' "$file")
          filename=$(basename "$file" .json)
          if [[ "$template_id" != "$filename" ]]; then
            echo "❌ Template ID ($template_id) doesn't match filename ($filename)"
            valid=false
            continue
          fi
          
          # Check for reasonable limits
          image_count=$(jq '.images | length' "$file")
          if [[ $image_count -gt 1000 ]]; then
            echo "❌ Template has too many images ($image_count > 1000)"
            valid=false
            continue
          fi
          
          tier_count=$(jq '.tiers | length' "$file")
          if [[ $tier_count -gt 50 ]]; then
            echo "❌ Template has too many tiers ($tier_count > 50)"
            valid=false
            continue
          fi
          
          # Check file size (should be reasonable)
          file_size=$(stat -c%s "$file")
          if [[ $file_size -gt 10485760 ]]; then  # 10MB limit
            echo "❌ Template file too large (${file_size} bytes > 10MB)"
            valid=false
            continue
          fi
          
          echo "✅ File $file is valid"
        done
        
        if [[ "$valid" == "true" ]]; then
          echo "✅ All template files are valid"
          echo "VALIDATION_PASSED=true" >> $GITHUB_ENV
        else
          echo "❌ Validation failed"
          echo "VALIDATION_PASSED=false" >> $GITHUB_ENV
        fi

    - name: Enable auto-merge on success
      if: env.VALIDATION_PASSED == 'true' && env.SAFE_CHANGES == 'true'
      run: |
        echo "All validations passed. Enabling auto-merge..."
        
        # Enable auto-merge for this PR
        gh pr merge ${{ github.event.pull_request.number }} --squash --auto
        
        echo "✅ Auto-merge enabled for PR #${{ github.event.pull_request.number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add validation labels
      if: env.VALIDATION_PASSED == 'true' && env.SAFE_CHANGES == 'true'
      run: |
        # Add labels to indicate validation passed
        gh pr edit ${{ github.event.pull_request.number }} --add-label "validation-passed,ready-to-merge"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on validation failure
      if: env.VALIDATION_PASSED == 'false' || env.SAFE_CHANGES == 'false'
      run: |
        comment="❌ **Template validation failed**\n\n"
        
        if [[ "${{ env.VALIDATION_PASSED }}" == "false" ]]; then
          comment+="**Template validation errors detected.** Please check that your template:\n"
          comment+="- ✅ Is valid JSON\n"
          comment+="- ✅ Contains required fields: id, name, images, tiers\n"
          comment+="- ✅ Has template ID matching the filename\n"
          comment+="- ✅ Doesn't exceed size limits (1000 images, 50 tiers, 10MB file)\n\n"
        fi
        
        if [[ "${{ env.SAFE_CHANGES }}" == "false" ]]; then
          comment+="**Unsafe changes detected.** This PR:\n"
          comment+="- ✅ Should only add new template JSON files\n"
          comment+="- ✅ Should not modify existing files\n"
          comment+="- ✅ Should only touch the templates/ directory\n\n"
        fi
        
        comment+="Please fix these issues and push updates to this PR for re-validation."
        
        gh pr comment ${{ github.event.pull_request.number }} --body "$comment"
        
        # Add failure label
        gh pr edit ${{ github.event.pull_request.number }} --add-label "validation-failed"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add success comment
      if: env.VALIDATION_PASSED == 'true' && env.SAFE_CHANGES == 'true'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "🎉 **Template validation passed!** ✅\n\nYour template has been automatically validated and **auto-merge has been enabled**. The PR will be automatically merged once all required checks pass.\n\n**Validation Results:**\n- ✅ Valid JSON structure\n- ✅ Required fields present\n- ✅ Template ID matches filename\n- ✅ Within size limits\n- ✅ Safe changes only\n\nThank you for your contribution to TierMaker2! 🚀"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}